// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3XYP7U3_GNfynDqzcQmznjh6b1sdBXSM',
    appId: '1:249383667201:web:397d8112e3213f65a2e200',
    messagingSenderId: '249383667201',
    projectId: 'absensiarduino-fd0f2',
    authDomain: 'absensiarduino-fd0f2.firebaseapp.com',
    storageBucket: 'absensiarduino-fd0f2.appspot.com',
    measurementId: 'G-V324W899SD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGB1WwvXm7Vfcegh2cGUH8s9BT2g23y10',
    appId: '1:249383667201:android:773f83a26c61cc51a2e200',
    messagingSenderId: '249383667201',
    projectId: 'absensiarduino-fd0f2',
    storageBucket: 'absensiarduino-fd0f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA06YmvFPklvefsFYCTah1URhSWMI_-AhE',
    appId: '1:249383667201:ios:87d15135073dce30a2e200',
    messagingSenderId: '249383667201',
    projectId: 'absensiarduino-fd0f2',
    storageBucket: 'absensiarduino-fd0f2.appspot.com',
    iosClientId: '249383667201-echhhg61kkh3r7b9s0drdpirm9kk39t0.apps.googleusercontent.com',
    iosBundleId: 'com.example.absensiArduinoAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA06YmvFPklvefsFYCTah1URhSWMI_-AhE',
    appId: '1:249383667201:ios:87d15135073dce30a2e200',
    messagingSenderId: '249383667201',
    projectId: 'absensiarduino-fd0f2',
    storageBucket: 'absensiarduino-fd0f2.appspot.com',
    iosClientId: '249383667201-echhhg61kkh3r7b9s0drdpirm9kk39t0.apps.googleusercontent.com',
    iosBundleId: 'com.example.absensiArduinoAdmin',
  );
}
